import 'enums.dart';

/// An actionable tip generated by the recommendation engine.
class Recommendation {
  const Recommendation({
    required this.category,
    required this.priority,
    required this.message,
    required this.forStage,
  });

  /// Short label for the category, e.g. "Watering", "Sunlight", "Soil".
  final String category;

  final RecommendationPriority priority;

  /// The human-readable advice text.
  final String message;

  /// Which growth stage this recommendation applies to.
  final GrowthStage forStage;

  @override
  String toString() =>
      'Recommendation(category: $category, priority: $priority, '
      'stage: $forStage)';
}
